server:
  port : 0
  #port: 50002

spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9000
    compression:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: h2
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    url : jdbc:h2:mem:testdb
    username : sa
    password:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:13306/mydb
#    username: root
#    password: test1357

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
logging:
  level:
    com.example.catalogservice : DEBUG